services:
  dokuwiki-alpine:
    container_name: apache2
    image: braingremlin/alpine-php-apache:latest
    restart: unless-stopped
    ports:
      - ${EXTERNAL_PORT:-8888}:80 # la porta definita nel Dockerfile
    volumes:
      #- data:/var/www/localhost/htdocs
      #- backup:/home/backup
      - ${DATA_VOLUME:-data}:/var/www/localhost/htdocs
     # if you need to customize php.ini settings    
     #- /volume1/docker/dokuwiki/php/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - stack.env


volumes:
  data:
  backup:
